CREATE TABLE IF NOT EXISTS Prefeito (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    ID_Cidade INT UNSIGNED,
    PRIMARY KEY (ID),
    UNIQUE KEY (ID_Cidade),
    FOREIGN KEY (ID_Cidade) REFERENCES Cidade (ID)
);
