CREATE TABLE IF NOT EXISTS Empresa (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    CNPJ INT UNSIGNED,
    PRIMARY KEY (ID),
    UNIQUE KEY (CNPJ)
);

-- Cidade_Empresa
CREATE TABLE IF NOT EXISTS Empresa_Unidade (
    ID_Empresa INT UNSIGNED NOT NULL,
    ID_Cidade INT UNSIGNED NOT NULL,
    Sede TINYINT(1) NOT NULL,
    PRIMARY KEY (ID_Empresa, ID_Cidade)
);